FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
COPY . .

RUN npm install ; npm run build



FROM node:20-alpine
WORKDIR /app


COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/server.js ./server.js
COPY --from=build /app/.env .env

EXPOSE 80

CMD ["node", "server.js"]